### ISSUE TITLE
Keyboard keys randomly stop working on client (Wayland server to Windows client)

### ISSUE THREAD

**Issue by hunterzero99** [input-leap/input-leap#2124]
### What happened?

[input-leap-error occured.log](https://github.com/user-attachments/files/18095927/input-leap-error.occured.log)

Randomly after running for a long time input-leap will start sending garbage key presses to the client.  They'll sometimes do unintended commands on the client, like somehow hitting send on an email, opening new browser tabs, etc.  It's sort of like some modifier keys are stuck down or something.

I've been experiencing this issue since Wayland support was added, and it happens on both GNOME and KDE.  Stopping the input-leap server and restarting it fixes the issue until it randomly appears again.  Restarting the client does not fix it.  I'm still not confident I have a decent log of the issue, but I think the log shows what is happening when it starts sending _mask=0x2_ and _mask=0x0002_ for all key presses instead of _mask=0x0_ and _mask=0x0000_.  This starts showing up towards the end of the file I have attached, at [2024-12-11T07:35:26].

Server is linux running 3.0.2 release.
Client is Windows running 3.0.2 build.  There is nothing logged on the client out of the ordinary when this happens.

If there are any logs I can gather to help track this down a little more please let me know.

### Version

v3.0.2

### If applicable, where did you install Input Leap from?

Arch repo

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland

### What OS versions are you using?

Arch server with kernel 6.6.63-1-lts but happens on all kernels
Windows 11 client, but also happens on Windows 10.  I have no linux clients to test.

**Comment by LunaSquee** [comment]
This also happens seemingly at random on my Wayland (Arch Linux, KDE) host and macOS 15.1.1 (apple silicon) client setup.

**Comment by hunterzero99** [comment]
The 0x2 mask value I reported appears to correlate with the ctrl key being held down.  I'm not entirely sure how to work on debugging things, but for now I'm trying to dig into EiScreen.cpp in input-leap.  The bug could be in libei, though.

I'm also guessing that it might be related to [this recent change in libei documentation](https://gitlab.freedesktop.org/libinput/libei/-/commit/1152c038ee83064695a0f3e6e7461094c21f0563).  It sounds like a race condition where the control key gets reported as pressed down on the client when it is up on the server is possible.

**Comment by hunterzero99** [comment]
I'm fairly certain this has been fixed by changes in libei that are currently in git.  I'm going to close this for now.

**Comment by SnDream** [comment]
I had a similar problem with the same server/client, and it seems to me that it may have something to do with moving the mouse from Windows to Wayland while holding down CTRL, Windows still sees it as CTRL pressed, but only Wayland receives the CTRL release action. I will hold CTRL in Wayland when the problem occurs, move to Windows, release CTRL, and sometimes that solves the problem.

**Comment by SpiralBrad** [comment]
This exact same issue affects even the *current* versions of Synergy.

**Comment by MrCh1ppy** [comment]
This issue persists; synchronisation between my two Fedora 43 systems also encounters this problem, and with considerable frequency.
